import {
  Home,
  ShoppingCart,
  UtensilsCrossed,
  Car,
  Plane,
  Train,
  Bus,
  Coffee,
  Pizza,
  Apple,
  ShoppingBag,
  CreditCard,
  Wallet,
  DollarSign,
  Receipt,
  Tag,
  Gift,
  Heart,
  Star,
  Music,
  Film,
  Gamepad2,
  Book,
  GraduationCap,
  Briefcase,
  Building,
  Hospital,
  Stethoscope,
  Dumbbell,
  Footprints,
  Camera,
  Palette,
  Wrench,
  Hammer,
  Lightbulb,
  Zap,
  Flame,
  Droplet,
  Leaf,
  TreePine,
  Sun,
  Moon,
  Cloud,
  Umbrella,
  Snowflake,
  MessageSquare,
  Phone,
  Mail,
  Send,
  Users,
  User,
  UserPlus,
  Settings,
  Bell,
  Calendar,
  Clock,
  MapPin,
  Navigation,
  Globe,
  Lock,
  Key,
  Shield,
  AlertCircle,
  CheckCircle,
  XCircle,
  Info,
  HelpCircle,
  Search,
  Filter,
  Plus,
  Minus,
  Edit,
  Trash2,
  Save,
  Download,
  Upload,
  Share2,
  Copy,
  Link,
  ExternalLink,
  Eye,
  EyeOff,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  MoreVertical,
  MoreHorizontal,
  Menu,
  X,
  Check,
  type LucideIcon,
} from 'lucide-react';

export type IconType = 'emoji' | 'lucide';

export interface IconItem {
  id: string;
  value: string | LucideIcon;
  name: string;
  type: IconType;
  category: string;
}

export interface IconCategory {
  id: string;
  name: string;
  icon: string | LucideIcon;
  type: IconType;
}

// Emoji categories
export const emojiCategories: IconCategory[] = [
  { id: 'food', name: 'Comida', icon: '🍕', type: 'emoji' },
  { id: 'transport', name: 'Transporte', icon: '🚗', type: 'emoji' },
  { id: 'shopping', name: 'Compras', icon: '🛒', type: 'emoji' },
  { id: 'finance', name: 'Finanzas', icon: '💰', type: 'emoji' },
  { id: 'activities', name: 'Actividades', icon: '⚽', type: 'emoji' },
  { id: 'objects', name: 'Objetos', icon: '📱', type: 'emoji' },
  { id: 'nature', name: 'Naturaleza', icon: '🌳', type: 'emoji' },
  { id: 'symbols', name: 'Símbolos', icon: '⭐', type: 'emoji' },
];

// Lucide icon categories
export const lucideCategories: IconCategory[] = [
  { id: 'actions', name: 'Acciones', icon: Zap, type: 'lucide' },
  { id: 'navigation', name: 'Navegación', icon: Navigation, type: 'lucide' },
  { id: 'communication', name: 'Comunicación', icon: MessageSquare, type: 'lucide' },
  { id: 'finance', name: 'Finanzas', icon: DollarSign, type: 'lucide' },
  { id: 'objects', name: 'Objetos', icon: ShoppingBag, type: 'lucide' },
  { id: 'people', name: 'Personas', icon: Users, type: 'lucide' },
  { id: 'status', name: 'Estado', icon: CheckCircle, type: 'lucide' },
  { id: 'tools', name: 'Herramientas', icon: Wrench, type: 'lucide' },
];

// Emoji icons by category
export const emojiIcons: Record<string, IconItem[]> = {
  food: [
    { id: 'emoji-food-1', value: '🍕', name: 'Pizza', type: 'emoji', category: 'food' },
    { id: 'emoji-food-2', value: '🍔', name: 'Hamburguesa', type: 'emoji', category: 'food' },
    { id: 'emoji-food-3', value: '🍟', name: 'Papas Fritas', type: 'emoji', category: 'food' },
    { id: 'emoji-food-4', value: '🌮', name: 'Taco', type: 'emoji', category: 'food' },
    { id: 'emoji-food-5', value: '🌯', name: 'Burrito', type: 'emoji', category: 'food' },
    { id: 'emoji-food-6', value: '🍜', name: 'Ramen', type: 'emoji', category: 'food' },
    { id: 'emoji-food-7', value: '🍝', name: 'Spaghetti', type: 'emoji', category: 'food' },
    { id: 'emoji-food-8', value: '🍣', name: 'Sushi', type: 'emoji', category: 'food' },
    { id: 'emoji-food-9', value: '🍱', name: 'Bento', type: 'emoji', category: 'food' },
    { id: 'emoji-food-10', value: '🍛', name: 'Curry', type: 'emoji', category: 'food' },
    { id: 'emoji-food-11', value: '🍲', name: 'Sopa', type: 'emoji', category: 'food' },
    { id: 'emoji-food-12', value: '🥘', name: 'Paella', type: 'emoji', category: 'food' },
    { id: 'emoji-food-13', value: '🍳', name: 'Cocinar', type: 'emoji', category: 'food' },
    { id: 'emoji-food-14', value: '🥞', name: 'Panqueques', type: 'emoji', category: 'food' },
    { id: 'emoji-food-15', value: '🧇', name: 'Waffle', type: 'emoji', category: 'food' },
    { id: 'emoji-food-16', value: '🥓', name: 'Tocino', type: 'emoji', category: 'food' },
    { id: 'emoji-food-17', value: '🥐', name: 'Croissant', type: 'emoji', category: 'food' },
    { id: 'emoji-food-18', value: '🥨', name: 'Pretzel', type: 'emoji', category: 'food' },
    { id: 'emoji-food-19', value: '🍞', name: 'Pan', type: 'emoji', category: 'food' },
    { id: 'emoji-food-20', value: '🥖', name: 'Baguette', type: 'emoji', category: 'food' },
    { id: 'emoji-food-21', value: '🥯', name: 'Bagel', type: 'emoji', category: 'food' },
    { id: 'emoji-food-22', value: '🧀', name: 'Queso', type: 'emoji', category: 'food' },
    { id: 'emoji-food-23', value: '🥚', name: 'Huevo', type: 'emoji', category: 'food' },
    { id: 'emoji-food-24', value: '🍳', name: 'Huevo Frito', type: 'emoji', category: 'food' },
    { id: 'emoji-food-25', value: '🥗', name: 'Ensalada', type: 'emoji', category: 'food' },
    { id: 'emoji-food-26', value: '🥙', name: 'Wrap', type: 'emoji', category: 'food' },
    { id: 'emoji-food-27', value: '🥪', name: 'Sandwich', type: 'emoji', category: 'food' },
    { id: 'emoji-food-28', value: '🌭', name: 'Hot Dog', type: 'emoji', category: 'food' },
    { id: 'emoji-food-29', value: '🍖', name: 'Carne', type: 'emoji', category: 'food' },
    { id: 'emoji-food-30', value: '🍗', name: 'Pollo', type: 'emoji', category: 'food' },
    { id: 'emoji-food-31', value: '🥩', name: 'Carne Roja', type: 'emoji', category: 'food' },
    { id: 'emoji-food-32', value: '🥓', name: 'Tocino', type: 'emoji', category: 'food' },
    { id: 'emoji-food-33', value: '🍕', name: 'Pizza', type: 'emoji', category: 'food' },
    { id: 'emoji-food-34', value: '🍔', name: 'Hamburguesa', type: 'emoji', category: 'food' },
    { id: 'emoji-food-35', value: '🍟', name: 'Papas Fritas', type: 'emoji', category: 'food' },
    { id: 'emoji-food-36', value: '🌮', name: 'Taco', type: 'emoji', category: 'food' },
    { id: 'emoji-food-37', value: '🌯', name: 'Burrito', type: 'emoji', category: 'food' },
    { id: 'emoji-food-38', value: '🍜', name: 'Ramen', type: 'emoji', category: 'food' },
    { id: 'emoji-food-39', value: '🍝', name: 'Spaghetti', type: 'emoji', category: 'food' },
    { id: 'emoji-food-40', value: '🍣', name: 'Sushi', type: 'emoji', category: 'food' },
  ],
  transport: [
    { id: 'emoji-transport-1', value: '🚗', name: 'Auto', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-2', value: '🚕', name: 'Taxi', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-3', value: '🚙', name: 'SUV', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-4', value: '🚌', name: 'Bus', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-5', value: '🚎', name: 'Trolebús', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-6', value: '🏎️', name: 'Auto Deportivo', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-7', value: '🚓', name: 'Policía', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-8', value: '🚑', name: 'Ambulancia', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-9', value: '🚒', name: 'Bomberos', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-10', value: '🚐', name: 'Van', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-11', value: '🛻', name: 'Pickup', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-12', value: '🚚', name: 'Camión', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-13', value: '🚛', name: 'Camión Grande', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-14', value: '🚜', name: 'Tractor', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-15', value: '🏍️', name: 'Motocicleta', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-16', value: '🛵', name: 'Scooter', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-17', value: '🚲', name: 'Bicicleta', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-18', value: '🛴', name: 'Patineta', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-19', value: '🚁', name: 'Helicóptero', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-20', value: '✈️', name: 'Avión', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-21', value: '🛩️', name: 'Avión Pequeño', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-22', value: '🛫', name: 'Despegue', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-23', value: '🛬', name: 'Aterrizaje', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-24', value: '🚀', name: 'Cohete', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-25', value: '🚂', name: 'Tren', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-26', value: '🚃', name: 'Vagón', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-27', value: '🚄', name: 'Tren Rápido', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-28', value: '🚅', name: 'Tren Bala', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-29', value: '🚆', name: 'Metro', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-30', value: '🚇', name: 'Subterráneo', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-31', value: '🚈', name: 'Tren Ligero', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-32', value: '🚉', name: 'Estación', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-33', value: '🚊', name: 'Tranvía', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-34', value: '🚝', name: 'Monorraíl', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-35', value: '🚞', name: 'Tren Montaña', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-36', value: '🚟', name: 'Teleférico', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-37', value: '🚠', name: 'Telesilla', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-38', value: '🚡', name: 'Teleférico', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-39', value: '⛴️', name: 'Ferry', type: 'emoji', category: 'transport' },
    { id: 'emoji-transport-40', value: '🛥️', name: 'Lancha', type: 'emoji', category: 'transport' },
  ],
  shopping: [
    { id: 'emoji-shopping-1', value: '🛒', name: 'Carrito', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-2', value: '🛍️', name: 'Bolsas', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-3', value: '🛎️', name: 'Timbre', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-4', value: '💳', name: 'Tarjeta', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-5', value: '💰', name: 'Dinero', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-6', value: '💵', name: 'Billete', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-7', value: '💴', name: 'Yen', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-8', value: '💶', name: 'Euro', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-9', value: '💷', name: 'Libra', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-10', value: '💸', name: 'Dinero Volando', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-11', value: '💹', name: 'Gráfico', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-12', value: '🛒', name: 'Carrito', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-13', value: '🛍️', name: 'Bolsas', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-14', value: '🛎️', name: 'Timbre', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-15', value: '💳', name: 'Tarjeta', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-16', value: '💰', name: 'Dinero', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-17', value: '💵', name: 'Billete', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-18', value: '💴', name: 'Yen', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-19', value: '💶', name: 'Euro', type: 'emoji', category: 'shopping' },
    { id: 'emoji-shopping-20', value: '💷', name: 'Libra', type: 'emoji', category: 'shopping' },
  ],
  finance: [
    { id: 'emoji-finance-1', value: '💰', name: 'Dinero', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-2', value: '💵', name: 'Billete', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-3', value: '💴', name: 'Yen', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-4', value: '💶', name: 'Euro', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-5', value: '💷', name: 'Libra', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-6', value: '💸', name: 'Gasto', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-7', value: '💹', name: 'Gráfico', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-8', value: '💳', name: 'Tarjeta', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-9', value: '💎', name: 'Diamante', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-10', value: '🏦', name: 'Banco', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-11', value: '💼', name: 'Maletín', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-12', value: '📊', name: 'Gráfico', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-13', value: '📈', name: 'Subida', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-14', value: '📉', name: 'Bajada', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-15', value: '💱', name: 'Cambio', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-16', value: '💲', name: 'Símbolo', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-17', value: '💰', name: 'Dinero', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-18', value: '💵', name: 'Billete', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-19', value: '💴', name: 'Yen', type: 'emoji', category: 'finance' },
    { id: 'emoji-finance-20', value: '💶', name: 'Euro', type: 'emoji', category: 'finance' },
  ],
  activities: [
    { id: 'emoji-activities-1', value: '⚽', name: 'Fútbol', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-2', value: '🏀', name: 'Básquet', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-3', value: '🏈', name: 'Fútbol Americano', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-4', value: '⚾', name: 'Béisbol', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-5', value: '🎾', name: 'Tenis', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-6', value: '🏐', name: 'Voleibol', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-7', value: '🏉', name: 'Rugby', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-8', value: '🎱', name: 'Billar', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-9', value: '🏓', name: 'Ping Pong', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-10', value: '🏸', name: 'Bádminton', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-11', value: '🥊', name: 'Boxeo', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-12', value: '🥋', name: 'Artes Marciales', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-13', value: '🥅', name: 'Portería', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-14', value: '⛳', name: 'Golf', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-15', value: '🏹', name: 'Tiro con Arco', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-16', value: '🎣', name: 'Pesca', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-17', value: '🥌', name: 'Curling', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-18', value: '🎯', name: 'Diana', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-19', value: '🎮', name: 'Videojuegos', type: 'emoji', category: 'activities' },
    { id: 'emoji-activities-20', value: '🕹️', name: 'Joystick', type: 'emoji', category: 'activities' },
  ],
  objects: [
    { id: 'emoji-objects-1', value: '📱', name: 'Teléfono', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-2', value: '💻', name: 'Laptop', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-3', value: '⌚', name: 'Reloj', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-4', value: '📷', name: 'Cámara', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-5', value: '📹', name: 'Video', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-6', value: '📺', name: 'TV', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-7', value: '📻', name: 'Radio', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-8', value: '🎙️', name: 'Micrófono', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-9', value: '🎚️', name: 'Control', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-10', value: '🎛️', name: 'Panel', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-11', value: '📟', name: 'Beeper', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-12', value: '📠', name: 'Fax', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-13', value: '🔋', name: 'Batería', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-14', value: '🔌', name: 'Enchufe', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-15', value: '💡', name: 'Bombilla', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-16', value: '🔦', name: 'Linterna', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-17', value: '🕯️', name: 'Vela', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-18', value: '🧯', name: 'Extintor', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-19', value: '🛢️', name: 'Aceite', type: 'emoji', category: 'objects' },
    { id: 'emoji-objects-20', value: '💸', name: 'Dinero', type: 'emoji', category: 'objects' },
  ],
  nature: [
    { id: 'emoji-nature-1', value: '🌳', name: 'Árbol', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-2', value: '🌲', name: 'Pino', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-3', value: '🌴', name: 'Palmera', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-4', value: '🌱', name: 'Planta', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-5', value: '🌿', name: 'Hierba', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-6', value: '☘️', name: 'Trébol', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-7', value: '🍀', name: 'Trébol', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-8', value: '🍁', name: 'Hoja', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-9', value: '🍂', name: 'Hojas', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-10', value: '🍃', name: 'Hoja', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-11', value: '🌾', name: 'Trigo', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-12', value: '🌷', name: 'Tulipán', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-13', value: '🌹', name: 'Rosa', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-14', value: '🌺', name: 'Hibisco', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-15', value: '🌻', name: 'Girasol', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-16', value: '🌼', name: 'Flor', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-17', value: '🌸', name: 'Cerezo', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-18', value: '🌍', name: 'Tierra', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-19', value: '🌎', name: 'América', type: 'emoji', category: 'nature' },
    { id: 'emoji-nature-20', value: '🌏', name: 'Asia', type: 'emoji', category: 'nature' },
  ],
  symbols: [
    { id: 'emoji-symbols-1', value: '⭐', name: 'Estrella', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-2', value: '🌟', name: 'Estrella Brillante', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-3', value: '💫', name: 'Estrella Fugaz', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-4', value: '✨', name: 'Brillo', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-5', value: '❄️', name: 'Nieve', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-6', value: '💝', name: 'Corazón Regalo', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-7', value: '💖', name: 'Corazón Brillante', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-8', value: '💗', name: 'Corazón Creciente', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-9', value: '💓', name: 'Corazón Latiente', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-10', value: '💞', name: 'Corazones', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-11', value: '💕', name: 'Dos Corazones', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-12', value: '💟', name: 'Corazón Decorado', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-13', value: '☮️', name: 'Paz', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-14', value: '✝️', name: 'Cruz', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-15', value: '☪️', name: 'Media Luna', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-16', value: '🕉️', name: 'Om', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-17', value: '☸️', name: 'Rueda', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-18', value: '✡️', name: 'Estrella', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-19', value: '🔯', name: 'Estrella Seis', type: 'emoji', category: 'symbols' },
    { id: 'emoji-symbols-20', value: '🆔', name: 'ID', type: 'emoji', category: 'symbols' },
  ],
};

// Lucide icons by category
export const lucideIcons: Record<string, IconItem[]> = {
  actions: [
    { id: 'lucide-actions-1', value: Zap, name: 'Zap', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-2', value: Plus, name: 'Plus', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-3', value: Minus, name: 'Minus', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-4', value: Edit, name: 'Edit', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-5', value: Trash2, name: 'Trash', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-6', value: Save, name: 'Save', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-7', value: Download, name: 'Download', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-8', value: Upload, name: 'Upload', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-9', value: Share2, name: 'Share', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-10', value: Copy, name: 'Copy', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-11', value: Link, name: 'Link', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-12', value: ExternalLink, name: 'External Link', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-13', value: Eye, name: 'Eye', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-14', value: EyeOff, name: 'Eye Off', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-15', value: Search, name: 'Search', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-16', value: Filter, name: 'Filter', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-17', value: Check, name: 'Check', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-18', value: X, name: 'X', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-19', value: Flame, name: 'Flame', type: 'lucide', category: 'actions' },
    { id: 'lucide-actions-20', value: Lightbulb, name: 'Lightbulb', type: 'lucide', category: 'actions' },
  ],
  navigation: [
    { id: 'lucide-navigation-1', value: Navigation, name: 'Navigation', type: 'lucide', category: 'navigation' },
    { id: 'lucide-navigation-2', value: ChevronRight, name: 'Chevron Right', type: 'lucide', category: 'navigation' },
    { id: 'lucide-navigation-3', value: ChevronLeft, name: 'Chevron Left', type: 'lucide', category: 'navigation' },
    { id: 'lucide-navigation-4', value: ChevronUp, name: 'Chevron Up', type: 'lucide', category: 'navigation' },
    { id: 'lucide-navigation-5', value: ChevronDown, name: 'Chevron Down', type: 'lucide', category: 'navigation' },
    { id: 'lucide-navigation-6', value: ArrowRight, name: 'Arrow Right', type: 'lucide', category: 'navigation' },
    { id: 'lucide-navigation-7', value: ArrowLeft, name: 'Arrow Left', type: 'lucide', category: 'navigation' },
    { id: 'lucide-navigation-8', value: ArrowUp, name: 'Arrow Up', type: 'lucide', category: 'navigation' },
    { id: 'lucide-navigation-9', value: ArrowDown, name: 'Arrow Down', type: 'lucide', category: 'navigation' },
    { id: 'lucide-navigation-10', value: MapPin, name: 'Map Pin', type: 'lucide', category: 'navigation' },
    { id: 'lucide-navigation-11', value: Globe, name: 'Globe', type: 'lucide', category: 'navigation' },
    { id: 'lucide-navigation-12', value: Home, name: 'Home', type: 'lucide', category: 'navigation' },
    { id: 'lucide-navigation-13', value: Menu, name: 'Menu', type: 'lucide', category: 'navigation' },
    { id: 'lucide-navigation-14', value: MoreVertical, name: 'More Vertical', type: 'lucide', category: 'navigation' },
    { id: 'lucide-navigation-15', value: MoreHorizontal, name: 'More Horizontal', type: 'lucide', category: 'navigation' },
  ],
  communication: [
    { id: 'lucide-communication-1', value: MessageSquare, name: 'Message', type: 'lucide', category: 'communication' },
    { id: 'lucide-communication-2', value: Phone, name: 'Phone', type: 'lucide', category: 'communication' },
    { id: 'lucide-communication-3', value: Mail, name: 'Mail', type: 'lucide', category: 'communication' },
    { id: 'lucide-communication-4', value: Send, name: 'Send', type: 'lucide', category: 'communication' },
    { id: 'lucide-communication-5', value: Bell, name: 'Bell', type: 'lucide', category: 'communication' },
    { id: 'lucide-communication-6', value: Users, name: 'Users', type: 'lucide', category: 'communication' },
    { id: 'lucide-communication-7', value: User, name: 'User', type: 'lucide', category: 'communication' },
    { id: 'lucide-communication-8', value: UserPlus, name: 'User Plus', type: 'lucide', category: 'communication' },
  ],
  finance: [
    { id: 'lucide-finance-1', value: DollarSign, name: 'Dollar', type: 'lucide', category: 'finance' },
    { id: 'lucide-finance-2', value: CreditCard, name: 'Credit Card', type: 'lucide', category: 'finance' },
    { id: 'lucide-finance-3', value: Wallet, name: 'Wallet', type: 'lucide', category: 'finance' },
    { id: 'lucide-finance-4', value: Receipt, name: 'Receipt', type: 'lucide', category: 'finance' },
    { id: 'lucide-finance-5', value: Tag, name: 'Tag', type: 'lucide', category: 'finance' },
    { id: 'lucide-finance-6', value: ShoppingCart, name: 'Shopping Cart', type: 'lucide', category: 'finance' },
    { id: 'lucide-finance-7', value: ShoppingBag, name: 'Shopping Bag', type: 'lucide', category: 'finance' },
    { id: 'lucide-finance-8', value: Gift, name: 'Gift', type: 'lucide', category: 'finance' },
  ],
  objects: [
    { id: 'lucide-objects-1', value: ShoppingBag, name: 'Shopping Bag', type: 'lucide', category: 'objects' },
    { id: 'lucide-objects-2', value: Camera, name: 'Camera', type: 'lucide', category: 'objects' },
    { id: 'lucide-objects-3', value: Palette, name: 'Palette', type: 'lucide', category: 'objects' },
    { id: 'lucide-objects-4', value: Wrench, name: 'Wrench', type: 'lucide', category: 'objects' },
    { id: 'lucide-objects-5', value: Hammer, name: 'Hammer', type: 'lucide', category: 'objects' },
    { id: 'lucide-objects-6', value: Lightbulb, name: 'Lightbulb', type: 'lucide', category: 'objects' },
    { id: 'lucide-objects-7', value: Book, name: 'Book', type: 'lucide', category: 'objects' },
    { id: 'lucide-objects-8', value: Gamepad2, name: 'Gamepad', type: 'lucide', category: 'objects' },
    { id: 'lucide-objects-9', value: Music, name: 'Music', type: 'lucide', category: 'objects' },
    { id: 'lucide-objects-10', value: Film, name: 'Film', type: 'lucide', category: 'objects' },
  ],
  people: [
    { id: 'lucide-people-1', value: Users, name: 'Users', type: 'lucide', category: 'people' },
    { id: 'lucide-people-2', value: User, name: 'User', type: 'lucide', category: 'people' },
    { id: 'lucide-people-3', value: UserPlus, name: 'User Plus', type: 'lucide', category: 'people' },
    { id: 'lucide-people-4', value: Briefcase, name: 'Briefcase', type: 'lucide', category: 'people' },
    { id: 'lucide-people-5', value: GraduationCap, name: 'Graduation Cap', type: 'lucide', category: 'people' },
  ],
  status: [
    { id: 'lucide-status-1', value: CheckCircle, name: 'Check Circle', type: 'lucide', category: 'status' },
    { id: 'lucide-status-2', value: XCircle, name: 'X Circle', type: 'lucide', category: 'status' },
    { id: 'lucide-status-3', value: AlertCircle, name: 'Alert Circle', type: 'lucide', category: 'status' },
    { id: 'lucide-status-4', value: Info, name: 'Info', type: 'lucide', category: 'status' },
    { id: 'lucide-status-5', value: HelpCircle, name: 'Help Circle', type: 'lucide', category: 'status' },
    { id: 'lucide-status-6', value: Star, name: 'Star', type: 'lucide', category: 'status' },
    { id: 'lucide-status-7', value: Heart, name: 'Heart', type: 'lucide', category: 'status' },
  ],
  tools: [
    { id: 'lucide-tools-1', value: Wrench, name: 'Wrench', type: 'lucide', category: 'tools' },
    { id: 'lucide-tools-2', value: Hammer, name: 'Hammer', type: 'lucide', category: 'tools' },
    { id: 'lucide-tools-3', value: Settings, name: 'Settings', type: 'lucide', category: 'tools' },
    { id: 'lucide-tools-4', value: Key, name: 'Key', type: 'lucide', category: 'tools' },
    { id: 'lucide-tools-5', value: Lock, name: 'Lock', type: 'lucide', category: 'tools' },
    { id: 'lucide-tools-6', value: Shield, name: 'Shield', type: 'lucide', category: 'tools' },
    { id: 'lucide-tools-7', value: Search, name: 'Search', type: 'lucide', category: 'tools' },
    { id: 'lucide-tools-8', value: Filter, name: 'Filter', type: 'lucide', category: 'tools' },
  ],
};

// Get all icons for a category
export function getIconsByCategory(categoryId: string, type: IconType): IconItem[] {
  if (type === 'emoji') {
    return emojiIcons[categoryId] || [];
  } else {
    return lucideIcons[categoryId] || [];
  }
}

// Get all categories for a type
export function getCategoriesByType(type: IconType): IconCategory[] {
  if (type === 'emoji') {
    return emojiCategories;
  } else {
    return lucideCategories;
  }
}

// Get icon by value (for finding selected icon)
export function findIconByValue(value: string | LucideIcon, type: IconType): IconItem | undefined {
  const categories = type === 'emoji' ? emojiCategories : lucideCategories;
  
  for (const category of categories) {
    const icons = getIconsByCategory(category.id, type);
    const found = icons.find(icon => {
      if (type === 'emoji') {
        return icon.value === value;
      } else {
        // For lucide icons, compare by name since components can't be compared directly
        return typeof icon.value !== 'string' && typeof value !== 'string' && 
               (icon.value as any).displayName === (value as any).displayName;
      }
    });
    if (found) return found;
  }
  return undefined;
}

